on:
  push:
    branches:
      - master

name: 🚀 Production deploy on merge
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: cluster.hostliner.cz
          username: ${{ secrets.FTP_PASSWORD_CLUSTER }}
          password: ${{ secrets.FTP_USERNAME_CLUSTER }}
          protocol: ftps
          port: 21
          local-dir: ./output/
          server-dir: cdn.patrikvadura.cz/saroli/emailing/
          state-name: .production.json
